Updated consumer contract test pipeline

diff --git a/.github/workflows/consumer-contract-tests.yml b/.github/workflows/consumer-contract-tests.yml
--- a/.github/workflows/consumer-contract-tests.yml
+++ b/.github/workflows/consumer-contract-tests.yml
@@ -12,13 +12,101 @@ name: Consumer contract tests
 
 
 on:
+  pull_request:
+    branches: [ main ]
+    paths-ignore: [ '**.md' ]
   push:
     branches: [ main ]
     paths-ignore: [ '**.md' ]
 
+env:
+  PUBLISH_CONTRACTS_RUN_NAME: 'publish-contracts-${{ github.event.repository.name }}-${{ github.run_id }}-${{ github.run_attempt }}'
+  CAN_I_DEPLOY_RUN_NAME: 'can-i-deploy-${{ github.event.repository.name }}-${{ github.run_id }}-${{ github.run_attempt }}'
+
 jobs:
+  bump-check:
+    runs-on: ubuntu-latest
+    outputs:
+      is-bump: ${{ steps.skiptest.outputs.is-bump }}
+    steps:
+      - uses: actions/checkout@v3
+      - name: Skip version bump merges
+        id: skiptest
+        uses: ./.github/actions/bump-skip
+        with:
+          event-name: ${{ github.event_name }}
+
+    # The primary objective of this section is to carefully control the dispatching of tags,
+    # ensuring it only occurs during the 'Tag, publish, deploy' workflow.
+    # However, a challenge arises with contract tests, as they require knowledge of the upcoming tag
+    # before the actual deployment. To address this, we leverage the dry run feature provided by bumper.
+    # This allows us to obtain the next tag for publishing contracts and verifying consumer pacts without
+    # triggering the tag dispatch. This approach sidesteps the need for orchestrating multiple workflows,
+    # simplifying our implementation.
+    #
+    # We regulate the tag job to meet the following requirements according to the trigger event type:
+    # 1. pull_request event (due to opening or updating of PR branch):
+    #      dry-run flag is set to false
+    #         this allows the new semver tag #major.#minor.#patch-#commit to be used to identity pacticipant version for development purpose
+    #         PR has no effect on the value of the latest tag in settings.gradle on disk
+    # 2. PR merge to main, this triggers a push event on the main branch:
+    #      dry-run flag is set to true
+    #         this allows the new semver tag #major.#minor.#patch to be used to identity pacticipant version, and
+    #         this action will not update the value of the latest tag in settings.gradle on disk
+    #
+    # Note: All workflows from the same PR merge should have the same copy of settings.gradle on disk,
+    # which should be the one from the HEAD of the main branch before the workflow starts running
+    regulated-tag-job:
+      needs: [ bump-check ]
+      if: ${{ needs.bump-check.outputs.is-bump == 'no' }}
+      uses: ./.github/workflows/tag.yml
+      with:
+        # The 'ref' parameter ensures that the consumer version is postfixed with the HEAD commit of the PR branch,
+        # facilitating cross-referencing of a pact between Pact Broker and GitHub.
+        ref: ${{ github.head_ref || '' }}
+        # The 'dry-run' parameter prevents the new tag from being dispatched.
+        dry-run: true
+        release-branches: main
+      secrets: inherit
+
+  init-github-context:
+    runs-on: ubuntu-latest
+    needs: [ bump-check ]
+    if: ${{ needs.bump-check.outputs.is-bump == 'no' }}
+    outputs:
+      repo-branch: ${{ steps.extract-branch.outputs.repo-branch }}
+      repo-version: ${{ steps.extract-branch.outputs.repo-version }}
+
+    steps:
+      - uses: actions/checkout@v3
+      - id: extract-branch
+        run: |
+          GITHUB_EVENT_NAME=${{ github.event_name }}
+          if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
+            GITHUB_REF=${{ github.ref }}
+            GITHUB_SHA=${{ github.sha }}
+          elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
+            GITHUB_REF=refs/heads/${{ github.head_ref }}
+            GITHUB_SHA=${{ github.event.pull_request.head.sha }}
+          elif [[ "$GITHUB_EVENT_NAME" == "merge_group" ]]; then
+            GITHUB_REF=refs/heads/${{ github.head_ref }}
+          else
+            echo "Failed to extract branch information"
+            exit 1
+          fi
+          echo "repo-branch=${GITHUB_REF/refs\/heads\//""}" >> $GITHUB_OUTPUT
+          echo "repo-version=${GITHUB_SHA}" >> $GITHUB_OUTPUT
+      - name: Echo repo and branch information
+        run: |
+          echo "repo-owner=${{ github.repository_owner }}"
+          echo "repo-name=${{ github.event.repository.name }}"
+          echo "repo-branch=${{ steps.extract-branch.outputs.repo-branch }}"
+          echo "repo-version=${{ steps.extract-branch.outputs.repo-version }}"
+
   cbas-contract-tests:
     runs-on: ubuntu-latest
+    needs: [ bump-check, init-github-context ]
+    if: ${{ needs.bump-check.outputs.is-bump == 'no' }}
     outputs:
       pact-b64: ${{ steps.encode-pact.outputs.pact-b64 }}
 
@@ -42,13 +130,21 @@ jobs:
     needs: [ cbas-contract-tests ]
     steps:
       - name: Dispatch to terra-github-workflows
-        uses: broadinstitute/workflow-dispatch@v3
+        uses: broadinstitute/workflow-dispatch@v4.0.0
         with:
+          run-name: "${{ env.PUBLISH_CONTRACTS_RUN_NAME }}"
           workflow: .github/workflows/publish-contracts.yaml
           repo: broadinstitute/terra-github-workflows
           ref: refs/heads/main
           token: ${{ secrets.BROADBOT_TOKEN }} # GitHub token for access to kick off a job in the private repo
-          inputs: '{ "pact-b64": "${{ needs.cbas-contract-tests.outputs.pact-b64 }}", "repo-owner": "DataBiosphere", "repo-name": "cbas", "repo-branch": "main" }'
+          inputs: '{
+            "run-name": "${{ env.PUBLISH_CONTRACTS_RUN_NAME }}",
+            "pact-b64": "${{ needs.cbas-contract-tests.outputs.pact-b64 }}",
+            "repo-owner": "${{ github.repository_owner }}",
+            "repo-name": "${{ github.event.repository.name }}",
+            "repo-branch": "${{ needs.init-github-context.outputs.repo-branch }}",
+            "release-tag": "${{ needs.regulated-tag-job.outputs.new-tag }}"
+          }'
 
 ## Deactivated until WM-2191 lands
 #  can-i-deploy:
@@ -56,10 +152,15 @@ jobs:
 #    needs: [ init-github-context, publish-contracts ]
 #    steps:
 #      - name: Dispatch to terra-github-workflows
-#        uses: broadinstitute/workflow-dispatch@v3
+#        uses: broadinstitute/workflow-dispatch@v4.0.0
 #        with:
+#          run-name: "${{ env.CAN_I_DEPLOY_RUN_NAME }}"
 #          workflow: .github/workflows/can-i-deploy.yaml
 #          repo: broadinstitute/terra-github-workflows
 #          ref: refs/heads/main
 #          token: ${{ secrets.BROADBOT_TOKEN }} # GitHub token for access to kick off a job in the private repo
-#          inputs: '{ "pacticipant": "cbas", "version": "${{ needs.init-github-context.outputs.repo-version }}" }'
+#          inputs: '{
+#            "run-name": "${{ env.CAN_I_DEPLOY_RUN_NAME }}",
+#            "pacticipant": "cbas",
+#            "version": "${{ needs.regulated-tag-job.outputs.new-tag }}"
+#          }'
