WM-2100: Update terra-helmfile on publish (#183)

diff --git a/.github/workflows/tag-and-publish.yml b/.github/workflows/tag-and-publish.yml
--- a/.github/workflows/tag-and-publish.yml
+++ b/.github/workflows/tag-and-publish.yml
@@ -119,3 +119,41 @@ jobs:
           git config --global user.email "broadbot@broadinstitute.org"
           git commit -am "${{ steps.ensure-jira-id.outputs.JIRA_ID }}: Auto update CBAS version to $HELM_NEW_TAG"
           git push https://broadbot:$BROADBOT_TOKEN@github.com/broadinstitute/cromwhelm.git main
+          cd -
+
+      - name: Clone terra-helmfile
+        uses: actions/checkout@v3
+        with:
+          repository: broadinstitute/terra-helmfile
+          token: ${{ secrets.BROADBOT_TOKEN }} # Has to be set at checkout AND later when pushing to work
+          path: terra-helmfile
+
+      - name: Update workflows-app in terra-helmfile
+        run: |
+          set -e
+          cd terra-helmfile
+          HELM_CUR_TAG=$(grep "/cbas:" charts/workflows-app/values.yaml | sed "s,.*/cbas:,,")
+          HELM_NEW_TAG=${{ steps.tag.outputs.tag }}
+          [[ -n "$HELM_CUR_TAG" && -n "$HELM_NEW_TAG" ]]
+          sed -i "s/$HELM_CUR_TAG/$HELM_NEW_TAG/" charts/workflows-app/values.yaml
+          cd -
+
+      - name: Make PR in terra-helmfile
+        env:
+          BROADBOT_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
+          GH_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
+        run: |
+          set -e
+          JIRA_ID=${{ steps.find-jira-id.outputs.JIRA_ID }}
+          if [[ $JIRA_ID == "missing" ]]; then
+            echo "JIRA_ID missing, PR to terra-helmfile will not be created"
+            exit 0;
+          fi
+          cd terra-helmfile
+          git checkout -b ${JIRA_ID}-cbas-update-${HELM_NEW_TAG}
+          git config --global user.name "broadbot"
+          git config --global user.email "broadbot@broadinstitute.org"
+          git commit -am "${JIRA_ID}: Auto update CBAS to $HELM_NEW_TAG in workflows-app"
+          git push -u origin ${JIRA_ID}-cbas-update-${HELM_NEW_TAG}
+          gh pr create --title "${JIRA_ID}: auto update CBAS version to $HELM_NEW_TAG in workflows-app" --body "${JIRA_ID} helm chart update" --label "automerge"
+          cd -
